### ISSUE TITLE
Buttons no longer work?

### ISSUE THREAD

**Issue by ghost** [janrueth/SiriServerCore#49]
Hey, I've just noticed that the buttons on screen, like when multiple numbers are listed or you have to press "cancel" or "send", no longer work, they just display the selection on the screen as if you had dictated it. Anyone having this issue?

**Comment by ghost** [comment]
Well I just updated everything to the newest fork and the problem still stands...

**Comment by ghost** [comment]
Also, I can still dictate my selection, but the on screen button doesn't work.

**Comment by janrueth** [comment]
I'll look into that

**Comment by janrueth** [comment]
can confirm this

**Comment by janrueth** [comment]
And now it is fixed!

**Comment by SimonTurp** [comment]
I still have this issue. Comes up with a CommandIgnored on server.
